<?php

/**
 * @file
 * Primary module hooks for Formation 1 module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function formation_1_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.formation_1':
      return '<p>L\'aide du module</p>';
  }
}

/**
 * Implements hook_theme().
 */
function formation_1_theme($existing, $type, $theme, $path) {
  return [
    'formation_1_index_3' => [
      'template' => 'formation_1_index_3',
      'variables' => [
        'title' => 'titre par défaut',
      ]
    ]
  ];
}
